Add new integration tests, improve error handling (#16)
- New integration tests.
- Improved error handling if the APIs return no JSON (plain 500).

diff --git a/integration/env/myver b/integration/env/myver
--- a/integration/env/myver
+++ b/integration/env/myver
@@ -4,14 +4,25 @@
 
 # myver -c defaults to outputting "true".
 # Set MVS_IS_CONSOLE to a value other than "true" to simulate running on some other host.
+
 if [ "$1" = "-c" ]
 then
+    if [ "${MYVER_FAIL_IS_CONSOLE:-false}" = "true" ];
+    then
+        echo "fail to run myver"
+        exit 1
+    fi
     echo "${MVS_IS_CONSOLE:-true}"
     exit 0
 fi
 
 if [ "$1" = "-vh" ]
 then
+    if [ "${MYVER_FAIL_HOSTNAME:-false}" = "true" ];
+    then
+        echo "fail to run myver"
+        exit 1
+    fi
     if [ "${MVS_INVALID_CERT:-false}" = "true" ];
     then
         echo "nocert"
